### ISSUE TITLE
Crashes on Load: You mixed Tabs and Spaces

### ISSUE THREAD

**Issue by FeralBytes** [RoboYorkie/Godot_RegularPolygon2D#1]
Otherwise Awesome Plugin! Thank you.
I have a Linux OS and Using Godot 3.2 Beta 1.
Particularly this file: res://addons/regular_polygon2d_node/regular_polygon2d_node.gd.
I personally would prefer all spaces instead of tabs, but that is just my preference and I converted the scripts on load.

**Comment by imsamuka** [comment]
Created #4 to solve this, but the creator hasn't done anything in Github for almost 2 years...

**Comment by RoboYorkie** [comment]
Sorry for the very late response. I created this repo a long time ago and didn't see notifications from GitHub :) Happy and surprise to learn that some people have found the code here useful.

**Comment by RoboYorkie** [comment]
#4 was merged, so closing this now.
